name: OnePub CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  test_and_dry_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 1. We need Flutter, not just Dart
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install OnePub CLI
        run: dart pub global activate onepub

      - name: Authenticate with OnePub
        run: |
          export ONEPUB_TOKEN=${{ secrets.ONEPUB_TOKEN }}
          onepub import

      # 2. Use 'flutter pub' instead of 'dart pub'
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Dry Run Publish
        run: flutter pub publish --dry-run

  publish:
    needs: test_and_dry_run
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install OnePub CLI
        run: dart pub global activate onepub

      - name: Authenticate & Publish
        run: |
          export ONEPUB_TOKEN=${{ secrets.ONEPUB_TOKEN }}
          onepub import
          flutter pub publish --force